// SPDX-License-Identifier: MIT
// Author:  Giovanni Santini
// Mail:    giovanni.santini@proton.me
// Github:  @San7o

#ifndef _MICRO_KEY_H
#define _MICRO_KEY_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum MicroKey
{
  MICRO_KEY_NONE = 0,
  MICRO_KEY_UNKNOWN,

  // PRINTABLE KEYS
  MICRO_KEY_SPACE,
  MICRO_KEY_APOSTROPHE,
  MICRO_KEY_COMMA,
  MICRO_KEY_MINUS,
  MICRO_KEY_PERIOD,
  MICRO_KEY_SLASH,
  MICRO_KEY_D0,
  MICRO_KEY_D1,
  MICRO_KEY_D2,
  MICRO_KEY_D3,
  MICRO_KEY_D4,
  MICRO_KEY_D5,
  MICRO_KEY_D6,
  MICRO_KEY_D7,
  MICRO_KEY_D8,
  MICRO_KEY_D9,
  MICRO_KEY_SEMICOLON,
  MICRO_KEY_EQUAL,
  MICRO_KEY_A,
  MICRO_KEY_B,
  MICRO_KEY_C,
  MICRO_KEY_D,
  MICRO_KEY_E,
  MICRO_KEY_F,
  MICRO_KEY_G,
  MICRO_KEY_H,
  MICRO_KEY_I,
  MICRO_KEY_J,
  MICRO_KEY_K,
  MICRO_KEY_L,
  MICRO_KEY_M,
  MICRO_KEY_N,
  MICRO_KEY_O,
  MICRO_KEY_P,
  MICRO_KEY_Q,
  MICRO_KEY_R,
  MICRO_KEY_S,
  MICRO_KEY_T,
  MICRO_KEY_U,
  MICRO_KEY_V,
  MICRO_KEY_W,
  MICRO_KEY_X,
  MICRO_KEY_Y,
  MICRO_KEY_Z,
  MICRO_KEY_LEFTBRACKET,
  MICRO_KEY_BACKSLASH,
  MICRO_KEY_RIGHTBRACKET,
  MICRO_KEY_GRAVEACCENT,
  MICRO_KEY_WORLD1,
  MICRO_KEY_WORLD2,

  // FUNCTION KEYS
  MICRO_KEY_ESCAPE,
  MICRO_KEY_ENTER,
  MICRO_KEY_TAB,
  MICRO_KEY_BACKSPACE,
  MICRO_KEY_INSERT,
  MICRO_KEY_DELETE,
  MICRO_KEY_RIGHT,
  MICRO_KEY_LEFT,
  MICRO_KEY_DOWN,
  MICRO_KEY_UP,
  MICRO_KEY_PAGEUP,
  MICRO_KEY_PAGEDOWN,
  MICRO_KEY_HOME,
  MICRO_KEY_END,
  MICRO_KEY_CAPSLOCK,
  MICRO_KEY_SCROLLLOCK,
  MICRO_KEY_NUMLOCK,
  MICRO_KEY_PRINTSCREEN,
  MICRO_KEY_PAUSE,
  MICRO_KEY_F1,
  MICRO_KEY_F2,
  MICRO_KEY_F3,
  MICRO_KEY_F4,
  MICRO_KEY_F5,
  MICRO_KEY_F6,
  MICRO_KEY_F7,
  MICRO_KEY_F8,
  MICRO_KEY_F9,
  MICRO_KEY_F10,
  MICRO_KEY_F11,
  MICRO_KEY_F12,
  MICRO_KEY_F13,
  MICRO_KEY_F14,
  MICRO_KEY_F15,
  MICRO_KEY_F16,
  MICRO_KEY_F17,
  MICRO_KEY_F18,
  MICRO_KEY_F19,
  MICRO_KEY_F20,
  MICRO_KEY_F21,
  MICRO_KEY_F22,
  MICRO_KEY_F23,
  MICRO_KEY_F24,
  MICRO_KEY_F25,

  // KEYPAD
  MICRO_KEY_KP0,
  MICRO_KEY_KP1,
  MICRO_KEY_KP2,
  MICRO_KEY_KP3,
  MICRO_KEY_KP4,
  MICRO_KEY_KP5,
  MICRO_KEY_KP6,
  MICRO_KEY_KP7,
  MICRO_KEY_KP8,
  MICRO_KEY_KP9,
  MICRO_KEY_KPDECIMAL,
  MICRO_KEY_KPDIVIDE,
  MICRO_KEY_KPMULTIPLY,
  MICRO_KEY_KPSUBTRACT,
  MICRO_KEY_KPADD,
  MICRO_KEY_KPENTER,
  MICRO_KEY_KPEQUAL,

  // MODIFIERS
  MICRO_KEY_LEFTSHIFT,
  MICRO_KEY_LEFTCONTROL,
  MICRO_KEY_LEFTALT,
  MICRO_KEY_LEFTSUPER,
  MICRO_KEY_RIGHTSHIFT,
  MICRO_KEY_RIGHTCONTROL,
  MICRO_KEY_RIGHTALT,
  MICRO_KEY_RIGHTSUPER,
  MICRO_KEY_MENU,
  
  MICRO_KEY_LAST = MICRO_KEY_MENU
} MicroKey;

#ifdef __cplusplus
}
#endif
  
#endif // _MICRO_KEY_H
